### ISSUE TITLE
Bump version to 4.1.1-j8. Make it build with java 8.

### ISSUE THREAD

**Issue by cquoss** [cquoss/apache-activemq-4.1.1#3]
# Make project build with java 8 under a separate version
Change the version of all sub-projects to 4.1.1-j8. Use versions plugin goal 'set' to achieve this. Disable creation of backup poms for this.

Make sure tests don't break.

Fire up the distribution and test this as well (using Apache Camel with to-jms route and ProducerTemplate.

Document every step done in comments on this issue.

Use branch 'issue-3' for this and hand in PR when done.

**Comment by cquoss** [comment]
Version bumped to 4.1.1-j8.

Added derby and activemq data files to .gitignore.

Fixed ${pom.[groupId|artifactId|version]} -> $project.[groupId|artifactId|version]}.

Bump Atomikos Version to 3.2.3 in activemq-test-atomikos.

Remove maven compiler plugin with source/target 1.5 from activemq-xmpp.

Remove maven-bundle-plugin (not found in maven central) from assembly pom.

Bump activeio-core version to 3.1.4.

Bump maven compiler plugin version to 3.8.1, set source/target to 8 in configuration.

Set build source encoding to UTF-8.

**Comment by cquoss** [comment]
As i suspected, but did not verify. Commit justed pushed does not build, even with tests skipped:

[ERROR] /C:/Users/Cleme/git/cquoss/apache-activemq-4.1.1/activemq-optional/src/main/java/org/apache/activemq/util/JmsLogAppenderSupport.java:[20,24] package org.apache.log4j does not exist

Working theory: version of activeio-core has been bumped, maybe transitive log4j dependency got lost on the way.

OK, added log4j dependency to optional. Also changed -Dmaven.test.skip=true to -DskipTests since test-jar of activemq-core is referenced in activemq-console.

Bump activemq-version in properties to 4.1.1-j8.

Bump version of surefire plugin to 3.0.0-M5 in order to make -DskipTests work.

**Comment by cquoss** [comment]
Now on to the tests. Enable tests again and run 'mvn clean verify'.

From 1487 tests run on activemq-core, there are 2 in error:

[ERROR] Tests run: 1487, Failures: 0, Errors: 2, Skipped: 0

These are:

[INFO] Running org.apache.activemq.config.BrokerXmlConfigFromJNDITest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.105 s <<< FAILURE! - in org.apache.activemq.config.BrokerXmlConfigFromJNDITest

==> javax.naming.NamingException: Invalid broker URL
	at org.apache.activemq.jndi.ActiveMQInitialContextFactory.getInitialContext(ActiveMQInitialContextFactory.java:72)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:695)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
	at javax.naming.InitialContext.init(InitialContext.java:244)
	at javax.naming.InitialContext.<init>(InitialContext.java:216)
	at org.apache.activemq.config.BrokerXmlConfigFromJNDITest.createConnectionFactory(BrokerXmlConfigFromJNDITest.java:50)

![image](https://user-images.githubusercontent.com/17934067/147872018-3657e746-4c56-418d-a7de-e07cb2d1be2e.png)

I'm pretty sure here C:\\... is inserted into the broker url, rendering it useless. So this does not work on windows and never has. Strange.

Let's put some log output here to verify.

Took some time, but finally - as i suspected:

2022-01-02 15:09:35,629 [main           ] DEBUG dReceiveWithTwoConnectionsTest - createConnectionFactory() [providerUrl=vm://localhost?brokerConfig=xbean:file:C:\Users\Cleme\git\cquoss\apache-activemq-4.1.1\activemq-core/src/test/resources/activemq.xml]

Try this with relative path (f.getPath()) instead in the URL.

This was to no avail. Try next with classpath instead of file.

This finally did the trick:

[INFO] Running org.apache.activemq.config.BrokerXmlConfigFromJNDITest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.504 s - in org.apache.activemq.config.BrokerXmlConfigFromJNDITest

Tests should run fine now.

---------------------

[INFO] Running org.apache.activemq.config.ConfigTest
[ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 43.738 s <<< FAILURE! - in org.apache.activemq.config.ConfigTest

==> org.springframework.beans.factory.BeanDefinitionStoreException: Line 1 in XML document from file [C:\Users\Cleme\git\cquoss\apache-activemq-4.1.1\activemq-core\src\test\resources\org\apache\activemq\config\sample-conf\jdbc-example.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.

![image](https://user-images.githubusercontent.com/17934067/147871893-86c53da6-1878-47e1-8cce-ad831eeedefc.png)

Strange, indeed ... removed the question marks.

---------------------------------

Slight drawback here, after having fixed the above we encounter 3 more:

[ERROR] Errors: 
[ERROR]   org.apache.activemq.broker.ft.QueueMasterSlaveTest#testSendReceive BeanCreationException
[ERROR]   org.apache.activemq.broker.ft.QueueMasterSlaveUsingMasterConnectorElementTest#testSendReceive BeanCreationException
[ERROR]   org.apache.activemq.broker.ft.TopicMasterSlaveTest#testSendReceive BeanCreationException
[INFO] 
[ERROR] Tests run: 1487, Failures: 0, Errors: 3, Skipped: 0

Cause on all 3 is:

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.apache.activemq.xbean.XBeanBrokerService' defined in class path resource [org/apache/activemq/broker/ft/master.xml]: Invocation of init method failed; nested exception is java.io.IOException: Failed to bind to server socket: tcp://localhost:62001 due to: java.net.BindException: Address already in use: JVM_Bind

tcp://localhost:62001 already in use ... strange again.

Something not torn down properly?

Second run these tests passed:

[INFO] Running org.apache.activemq.broker.ft.QueueMasterSlaveTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.597 s - in org.apache.activemq.broker.ft.QueueMasterSlaveTest
[INFO] Running org.apache.activemq.broker.ft.QueueMasterSlaveUsingMasterConnectorElementTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.639 s - in org.apache.activemq.broker.ft.QueueMasterSlaveUsingMasterConnectorElementTest
[INFO] Running org.apache.activemq.broker.ft.TopicMasterSlaveTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.703 s - in org.apache.activemq.broker.ft.TopicMasterSlaveTest

Oh, this is not good. Some sort of race condition or else. Not 100% reproducible. Not good, indeed.

------------------------------------

OMG. What is it with these tests? Now this:

[ERROR] Failures: 
[ERROR]   org.apache.activemq.config.ConfigTest#testJournaledJDBCConfig AssertionFailedError
[INFO] 
[ERROR] Tests run: 1487, Failures: 1, Errors: 0, Skipped: 0

junit.framework.AssertionFailedError: Should have created a derby directory at C:\Users\Cleme\git\cquoss\apache-activemq-4.1.1\activemq-core\target\test-data\testJournaledJDBCConfig\derbydb
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at org.apache.activemq.config.ConfigTest.testJournaledJDBCConfig(ConfigTest.java:97)

----------------------------------------

Next run went through, whole parent project build, no other test issues etc. elsewhere.

-------------------------------------

OMG, what is it with these f*cking tests? While trying to investigate the following error when trying to run the assembly after the successful build, i encountered the ConfigTest error above about the derbydb directory not being created as well as two new ones:

PS C:\Temp\apache-activemq-4.1.1-j8> .\bin\activemq.bat
Fehler: Hauptklasse org.apache.activemq.console.Main konnte nicht gefunden oder geladen werden

Here the new errors:

[ERROR] Errors: 
[ERROR]   org.apache.activemq.broker.ReconnectWithJMXEnabledTest#testTestUseConnectionCloseBrokerThenRestartInSameJVM IOException
[ERROR]   org.apache.activemq.broker.SpringTest#testSenderWithSpringXml BeanCreationException
[INFO] 
[ERROR] Tests run: 1487, Failures: 0, Errors: 2, Skipped: 0

The latter might be the tcp://localhost:60212 already in use encountered above, this url being used intensively during the tests. Let's check.

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'broker' defined in class path resource [org/apache/activemq/broker/spring.xml]: Invocation of init method failed; nested exception is java.io.IOException: Failed to bind to server socket: tcp://localhost:61616 due to: java.net.BindException: Address already in use: JVM_Bind

I'm right except for the port. Hmm. Teardown of brokers taking too much time? Done in separate threads? Maybe i should create a huge log file (it is large already: > 9 MBytes) by setting root logger to trace level to try to get proof for this. But then: logging is slow so this might prevent the error from showing up. 

Let's have a look at the former error, that look new indeed.

org.apache.activemq.broker.ReconnectWithJMXEnabledTest.testTestUseConnectionCloseBrokerThenRestartInSameJVM  Time elapsed: 0.536 s  <<< ERROR!
java.io.IOException: Failed to bind to server socket: tcp://localhost:61616 due to: java.net.BindException: Address already in use: JVM_Bind

It's actually the same error only transported in a different exception.

-------------------------

Before this issue gets completely out of hand i will now wrap up the changes so far, commit them, merge the branch and create separate issues for:

- error in assembly
- errors in tests
- errors in project setup (yes, there are some still)

The changes made in the meantime are (mostly related to activemq-core, if not all):

- add some more runtime directories to .gitignore
- code cleanups in BrokerXmlConfigFromJNDITest class
- add some logging to ConfigTest class and minor comment / code cleanups
-  remove the question marks from the beginning of jdbc-example.xml, fixing an error here
- add a logger to log4j configuration, minor code cleanups
- change surefire plugin configuration related to version bump to 3.0.0-M5

**Comment by cquoss** [comment]
Merged.
